export { fn_deadline } from './core/fn_deadline'
export { formatCadNumber } from './core/format-cad-number'
export { formatNumber } from './core/format-number'
export { formatPhoneNumber } from './core/format-phone-number'
export { getBase64 } from './core/get-base64'
export { getChunksFromString } from './core/get-chunks-from-string'
export { isNumber } from './core/is-number'
export { isValidEmail } from './core/is-valid-email'
export { isValidNationalCode } from './core/is-valid-national-code'
export { toCapitalize } from './core/to-capitalize'
export { toEnDigit } from './core/to-en-digit'
export { truncatedMiddleText } from './core/truncated-middle-text'
export { isJson } from './core/is-json'
export { removeEmptyKeys } from './core/remove-empty-keys'
export { ONE_SECOND, ONE_MINUTE, ONE_HOUR, ONE_DAY } from './core/const-time'
export { convertTimeToMilliseconds } from './core/convert-time-to-milliseconds'
export { enterFullScreen, exitFullScreen } from './core/handle-full-screen'
export { isArrayEqual } from './core/is-array-equal'
export { generateRandomNumber } from './core/generate-random-number'
export { wait } from './core/wait'
export { isContainsPersianCharacter } from './core/is-contains-persian-character'
export { isAllPersianCharacters } from './core/is-all-persian-characters'
export { isContainsEnglishCharacter } from './core/is-contains-english-character'
export { isAllEnglishCharacters } from './core/is-all-english-characters'
export { removeNullsFromArray } from './core/remove-nulls-from-array'
export { trimStringsStructure } from './core/trim-strings-structure'
export { toLowercase } from './core/to-lowercase'
export { tesnaString } from './string'
